apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-reader-writer-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
- kind: ServiceAccount
  name: default
  namespace: ocm-system
roleRef:
  kind: ClusterRole
  name: secret-reader-writer
  apiGroup: rbac.authorization.k8s.io
