# DON'T TOUCH IT, THIS WORKS!
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: replicator-cert
spec:
  # The name to be used on the ExternalSecrets
  externalSecretName: "replicator-cert-es"

  # This is a basic label selector to select the namespaces to deploy ExternalSecrets to.
  # you can read more about them here https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements
  namespaceSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: "In"
        values: ["ocm-system", "mpas-system", "mpas-sample-project"]

  # How often the ClusterExternalSecret should reconcile itself
  # This will decide how often to check and make sure that the ExternalSecrets exist in the matching namespaces
  refreshTime: "1m"

  # This is the spec of the ExternalSecrets to be created
  # The content of this was taken from our ExternalSecret example
  externalSecretSpec:
    secretStoreRef:
      name: secret-store-name
      kind: ClusterSecretStore

    refreshInterval: "1h"
    target:
      name: ocm-registry-tls-certs
    data:
    - secretKey: ca.crt # name of the property in the remote secret
      remoteRef:
        key: ocm-registry-tls-certs # name of the secret
        property: ca.crt
    - secretKey: tls.crt
      remoteRef:
        key: ocm-registry-tls-certs
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: ocm-registry-tls-certs
        property: tls.key
